package com.dsvv.cbcat.registry;

import com.dsvv.cbcat.CreateBigCannons_AdvancedTechnology;
import com.dsvv.cbcat.cartridge.ClusterProjectileCartridgeBlock;
import com.dsvv.cbcat.cartridge.IProjectileCartridgeBlockItem;
import com.dsvv.cbcat.cluster_munition.FuzedClusterProjectileBlock;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.List;
import java.util.function.Supplier;

public class TabRegister
{
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CreateBigCannons_AdvancedTechnology.MOD_ID);
    public static final Supplier<CreativeModeTab> SIMPLE_TAB = TABS
            .register("simple_tab", ()-> CreativeModeTab.builder()
            .title(Component.translatable("tab.cbc_at.simple"))
            .icon(() -> BlockRegister.SOLID_CARTRIDGE_BLOCK.asStack())
            .displayItems((p, o) -> o.acceptAll(List.of(new ItemStack[]{
                    BlockRegister.CAST_IRON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.CAST_IRON_FUME_EXTRACTOR.asStack(),
                    BlockRegister.CAST_IRON_SILENCER.asStack(),
                    BlockRegister.CAST_IRON_RIFLED_BARREL.asStack(),
                    BlockRegister.BRONZE_MUZZLE_BRAKE.asStack(),
                    BlockRegister.BRONZE_FUME_EXTRACTOR.asStack(),
                    BlockRegister.BRONZE_SILENCER.asStack(),
                    BlockRegister.BRONZE_RIFLED_BARREL.asStack(),
                    BlockRegister.STEEL_MUZZLE_BRAKE.asStack(),
                    BlockRegister.STEEL_FUME_EXTRACTOR.asStack(),
                    BlockRegister.STEEL_SILENCER.asStack(),
                    BlockRegister.BUILT_UP_STEEL_SILENCER.asStack(),
                    BlockRegister.STEEL_RIFLED_BARREL.asStack(),
                    BlockRegister.BUILT_UP_STEEL_RIFLED_BARREL.asStack(),
                    BlockRegister.NETHERSTEEL_MUZZLE_BRAKE.asStack(),
                    BlockRegister.NETHERSTEEL_FUME_EXTRACTOR.asStack(),
                    BlockRegister.NETHERSTEEL_SILENCER.asStack(),
                    BlockRegister.BUILT_UP_NETHERSTEEL_SILENCER.asStack(),
                    BlockRegister.NETHERSTEEL_RIFLED_BARREL.asStack(),
                    BlockRegister.BUILT_UP_NETHERSTEEL_RIFLED_BARREL.asStack(),
                    FuzedClusterProjectileBlock.getHighExplosiveWithImpactFuze(),
                    FuzedClusterProjectileBlock.getHighExplosiveFragmentationWithImpactFuze(),
                    FuzedClusterProjectileBlock.getHighExplosiveAntiTankWithImpactFuze(),
                    FuzedClusterProjectileBlock.getSmokeWithImpactFuze(),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.ARMOR_PIERCING_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.ARMOR_PIERCING_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.ARMOR_PIERCING_SHELL_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.ARMOR_PIERCING_SHELL_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.GRAPESHOT_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.GRAPESHOT_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.FLUID_SHELL_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.FLUID_SHELL_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.HIGH_EXPLOSIVE_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.HIGH_EXPLOSIVE_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SHRAPNEL_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SHRAPNEL_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SMOKE_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SMOKE_CASELESS_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SOLID_CARTRIDGE_BLOCK),
                    IProjectileCartridgeBlockItem.getWithPower(1, BlockRegister.SOLID_CASELESS_BLOCK),
                    ClusterProjectileCartridgeBlock.getChargedHighExplosiveWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getCaselessHighExplosiveWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getChargedHighExplosiveFragmentationWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getCaselessHighExplosiveFragmentationWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getChargedHighExplosiveAntiTankWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getCaselessHighExplosiveAntiTankWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getChargedSmokeWithImpactFuze(),
                    ClusterProjectileCartridgeBlock.getCaselessSmokeWithImpactFuze(),
                    BlockRegister.CAST_IRON_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.CAST_IRON_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.BRONZE_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.BRONZE_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.STEEL_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.STEEL_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.CAST_IRON_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.CAST_IRON_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.CAST_IRON_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.CAST_IRON_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.CAST_IRON_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.BRONZE_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.BRONZE_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.BRONZE_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.BRONZE_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.BRONZE_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.STEEL_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.STEEL_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.STEEL_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.STEEL_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.STEEL_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.CAST_IRON_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.CAST_IRON_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.CAST_IRON_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.CAST_IRON_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.CAST_IRON_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.BRONZE_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.BRONZE_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.BRONZE_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.BRONZE_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.BRONZE_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.STEEL_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.STEEL_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.STEEL_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.STEEL_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.STEEL_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    ItemRegister.APDS_ITEM.get().getCreativeTabCartridgeItem(),
                    ItemRegister.APDS_ITEM.asStack(),
                    ItemRegister.APDSFS_ITEM.get().getCreativeTabCartridgeItem(),
                    ItemRegister.APDSFS_ITEM.asStack(),
                    ItemRegister.HE_ITEM.get().getCreativeTabCartridgeItem(),
                    ItemRegister.HE_ITEM.asStack(),
                    ItemRegister.HEI_ITEM.get().getCreativeTabCartridgeItem(),
                    ItemRegister.HEI_ITEM.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.CAST_IRON_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.BRONZE_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.STEEL_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_AMMO_BOX.asStack(),
                    BlockRegister.CREATIVE_HEAVY_AUTOCANNON_AMMO_BOX.asStack(),
                    ItemRegister.HEAVY_AUTOCANNON_EMPTY_CARTRIDGE.asStack(),
                    ItemRegister.HA_AP_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_AP_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_AP_ITEM.asStack(),
                    ItemRegister.HA_APDS_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_APDS_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_APDS_ITEM.asStack(),
                    ItemRegister.HA_APDSFS_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_APDSFS_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_APDSFS_ITEM.asStack(),
                    ItemRegister.HA_HE_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_HE_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_HE_ITEM.asStack(),
                    ItemRegister.HA_HEF_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_HEF_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_HEF_ITEM.asStack(),
                    ItemRegister.HA_HEAT_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_HEAT_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_HEAT_ITEM.asStack(),
                    ItemRegister.HA_SMOKE_ITEM.get().getCreativeTabCartridgeItem(false),
                    ItemRegister.HA_SMOKE_ITEM.get().getCreativeTabCartridgeItem(true),
                    ItemRegister.HA_SMOKE_ITEM.asStack(),
                    BlockRegister.CAST_IRON_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.BRONZE_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.STEEL_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.CAST_IRON_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.BRONZE_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.STEEL_ROCKET_POD_BREECH.asStack(),
                    ItemRegister.AP_ROCKET_ITEM.get().getCreativeTabCartridgeItem(18),
                    ItemRegister.FLAK_ROCKET_ITEM.get().getCreativeTabCartridgeItem(18),
                    ItemRegister.HE_ROCKET_ITEM.get().getCreativeTabCartridgeItem(18),
                    ItemRegister.HEI_ROCKET_ITEM.get().getCreativeTabCartridgeItem(18),
                    /*BlockRegister.CAST_IRON_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.BRONZE_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.STEEL_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.CAST_IRON_MEDIUM_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.BRONZE_MEDIUM_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.STEEL_MEDIUM_ROCKET_POD_BREECH.asStack(),*/
                    BlockRegister.WROUGHT_IRON_MEDIUM_ROCKET_RAIL.asStack(),
                    BlockRegister.WROUGHT_IRON_MEDIUM_ROCKET_RAIL_BREECH.asStack(),
                    ItemRegister.MEDIUM_AP_ROCKET_ITEM.get().getCreativeTabCartridgeItem(36),
                    ItemRegister.MEDIUM_HE_ROCKET_ITEM.get().getCreativeTabCartridgeItem(36),
                    ItemRegister.MEDIUM_HEF_ROCKET_ITEM.get().getCreativeTabCartridgeItem(36),
                    ItemRegister.MEDIUM_HEAT_ROCKET_ITEM.get().getCreativeTabCartridgeItem(36),
                    BlockRegister.MUZZLE_BRAKE_MOULD.asStack(),
                    BlockRegister.FUME_EXTRACTOR_MOULD.asStack(),
                    BlockRegister.SILENCER_MOULD.asStack(),
                    BlockRegister.RIFLED_BARREL_MOULD.asStack(),
                    BlockRegister.AUTOCANNON_MUZZLE_BRAKE_MOULD.asStack(),
                    BlockRegister.AUTOCANNON_SILENCER_MOULD.asStack(),
                    BlockRegister.TWIN_AUTOCANNON_MUZZLE_BRAKE_MOULD.asStack(),
                    BlockRegister.TWIN_AUTOCANNON_BARREL_MOULD.asStack(),
                    BlockRegister.TWIN_AUTOCANNON_SILENCER_MOULD.asStack(),
                    BlockRegister.TWIN_AUTOCANNON_RECOIL_SPRING_MOULD.asStack(),
                    BlockRegister.TWIN_AUTOCANNON_BREECH_MOULD.asStack(),
                    BlockRegister.VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE_MOULD.asStack(),
                    BlockRegister.VERT_TWIN_AUTOCANNON_BARREL_MOULD.asStack(),
                    BlockRegister.VERT_TWIN_AUTOCANNON_SILENCER_MOULD.asStack(),
                    BlockRegister.VERT_TWIN_AUTOCANNON_RECOIL_SPRING_MOULD.asStack(),
                    BlockRegister.VERT_TWIN_AUTOCANNON_BREECH_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_MUZZLE_BRAKE_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_BARREL_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_SILENCER_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_RECOIL_SPRING_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_BREECH_MOULD.asStack(),
                    BlockRegister.HEAVY_AUTOCANNON_QFBREECH_MOULD.asStack(),
                    BlockRegister.ROCKET_POD_RAIL_MOULD.asStack(),
                    BlockRegister.ROCKET_POD_BREECH_MOULD.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_FUME_EXTRACTOR.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_SILENCER.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_RIFLED_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_BRONZE_FUME_EXTRACTOR.asStack(),
                    BlockRegister.UNBORED_BRONZE_SILENCER.asStack(),
                    BlockRegister.UNBORED_BRONZE_RIFLED_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_STEEL_FUME_EXTRACTOR.asStack(),
                    BlockRegister.UNBORED_STEEL_SILENCER.asStack(),
                    BlockRegister.UNBORED_STEEL_RIFLED_BARREL.asStack(),
                    BlockRegister.UNBORED_NETHERSTEEL_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_NETHERSTEEL_FUME_EXTRACTOR.asStack(),
                    BlockRegister.UNBORED_NETHERSTEEL_SILENCER.asStack(),
                    BlockRegister.UNBORED_NETHERSTEEL_RIFLED_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_BRONZE_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_BRONZE_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_STEEL_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_STEEL_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_BRONZE_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_BRONZE_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_BRONZE_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_STEEL_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_STEEL_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_STEEL_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_BRONZE_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_BRONZE_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_BRONZE_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_VERT_TWIN_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_STEEL_VERT_TWIN_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_VERT_TWIN_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_STEEL_VERT_TWIN_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_STEEL_VERT_TWIN_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_MUZZLE_BRAKE.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_SILENCER.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_RECOIL_SPRING.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_BREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_HEAVY_AUTOCANNON_QFBREECH.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_ROCKET_POD_BREECH.asStack(),
                    /*BlockRegister.UNBORED_CAST_IRON_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_BRONZE_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_STEEL_MEDIUM_ROCKET_POD_BARREL.asStack(),
                    BlockRegister.UNBORED_CAST_IRON_MEDIUM_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.UNBORED_BRONZE_MEDIUM_ROCKET_POD_BREECH.asStack(),
                    BlockRegister.UNBORED_STEEL_MEDIUM_ROCKET_POD_BREECH.asStack()*/
            })))
            .build());

    public static void register(IEventBus eventBus) {
        TABS.register(eventBus);
        CreateBigCannons_AdvancedTechnology.REGISTRATE.defaultCreativeTab((ResourceKey<CreativeModeTab>)null);
    }
}